version: '2'
services:
  ngBuilder:
    image: centos:angularCentos7
    build: ./
    user: root
    cap_add:
    - SYS_ADMIN
    privileged: true
    command: /usr/sbin/init
    command: npm install
    command: ng build
    hostname: 'localhost'
    container_name: ngBuilder
    volumes:
    - ./data:/usr/local/bin/ng-try
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
    - BACKEND_SERVER=172.31.37.239
    
