version: '2'
services:
  jenkinsdood:
    image: 'axltxl/jenkins-dood'
    hostname: 'localhost'
    container_name: jenkinsdood
    ports:
    - '29080:8080'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins_home:/var/jenkins_home
