version: '3'
services:
  nginx:
    image: nginx:nginxApline
    user: root
    cap_add:
    - SYS_ADMIN
    privileged: true
    build: ./
    ports:
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
#      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/config/sites-available:/etc/nginx/sites-available
      - ./data/nginx/config/sites-enabled:/etc/nginx/sites-enabled
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot